name: Android CI

on:

  pull_request:

    branches-ignore:

      - ''
      
  push:

    branches-ignore:

      - ''

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-22.04

    env:

      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      VERA_KEYSTORE_PASSWORD: ${{ secrets.VERA_KEYSTORE_PASSWORD }}

    steps:

      - name: Checkout

        uses: actions/checkout@v3

      - name: Get JRE 8

        uses: dawidd6/action-download-artifact@v2

        with:

          workflow: build.yml

          path: app_pojavlauncher/src/main/assets/components/jre

          workflow_conclusion: success

          repo: Vera-Firefly/android-openjdk-build

          branch: buildjre8

          name: jre8-pojav

      - name: Get JRE17

        uses: dawidd6/action-download-artifact@v2

        with:

          workflow: build.yml

          path: app_pojavlauncher/src/main/assets/components/jre-new

          workflow_conclusion: success

          repo: Vera-Firefly/android-openjdk-build

          branch: buildjre17

          name: jre17-pojav

      - name: Get LWJGL3

        uses: dawidd6/action-download-artifact@v2

        with:

          workflow: main.yml

          path: app_pojavlauncher/src/main/assets/components/lwjgl3

          workflow_conclusion: success

          repo: Vera-Firefly/lwjgl3-build

          branch: main

          name: lwjgl

      - uses: gradle/gradle-build-action@v2

        with:

          gradle-version: 7.6.1

      - name: Set up JDK 17

        uses: actions/setup-java@v3

        with:

          distribution: 'temurin'

          java-version: '17'

      - name: Build Release
        if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'exp_v3'
        run: |
          gradle :app_pojavlauncher:assemblerelease

      - name: Build Debug.apk

        run: |

          # Build the launcher

          gradle :app_pojavlauncher:assembleDebug

      - name: Upload release
        continue-on-error: true
        if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'exp_v3'
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app_pojavlauncher/build/outputs/apk/release/*

      - name: Upload APK

        uses: actions/upload-artifact@v3

        with:

          name: app-debug

          path: app_pojavlauncher/build/outputs/apk/debug/*

