name: Android CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      VERA_KEYSTORE_PASSWORD: ${{ secrets.VERA_KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set IS_OFFICIAL if in the Creator Repository
        if: github.repository_owner == 'Vera-Firefly'
        run: echo "IS_OFFICIAL=true" >> $GITHUB_ENV

      - name: Get Jre
        run: |
          echo "GET_JRE=1" >> $GITHUB_ENV

      - name: Get JRE
        run: |
          chmod +x scripts/getJre.sh
          sh scripts/getJre.sh

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: main
          name: lwjgl

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Release ${{matrix.arch}} .apk
        if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'main_v3'
        run: |
          chmod +x gradlew
          ./gradlew app_pojavlauncher:assemblerelease -Darch=${{matrix.arch}}

      - name: Build Debug ${{matrix.arch}} .apk
        run: |
          chmod +x gradlew
          ./gradlew app_pojavlauncher:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Release
        if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'main_v3'
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{matrix.arch}}
          path: app_pojavlauncher/build/outputs/apk/release/*

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{matrix.arch}}
          path: app_pojavlauncher/build/outputs/apk/debug/*

  buildnoruntime:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      VERA_KEYSTORE_PASSWORD: ${{ secrets.VERA_KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set IS_OFFICIAL if in the Creator Repository
        if: github.repository_owner == 'Vera-Firefly'
        run: echo "IS_OFFICIAL=true" >> $GITHUB_ENV

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: main
          name: lwjgl

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Debug-noruntime ${{matrix.arch}} .apk
        run: |
          chmod +x gradlew
          ./gradlew app_pojavlauncher:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{matrix.arch}}-noruntime
          path: app_pojavlauncher/build/outputs/apk/debug/*
