name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug-build:
        description: 'Trigger debug build'
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Add linting step
    - name: Lint Check
      run: ./gradlew lint

    # Add detekt analysis step
    - name: Detekt Analysis
      run: ./gradlew detekt

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-artifacts
        path: app/build/outputs/**

    # Add a step for debug build if manually triggered
    - name: Debug Build
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.debug-build
      run: ./gradlew buildDebug

    # Add a step to find and upload resource files
    - name: Find and Upload Resources
      run: |
        find . -name "your_resource_file_pattern" -type f -exec cp {} $GITHUB_WORKSPACE/ \;
      shell: bash
